# Generated by Django 4.1.5 on 2023-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='id',
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_date',
            field=models.DateTimeField(help_text='When snapshot was captured.', primary_key=True, serialize=False, verbose_name='Date & Time snapshot was collected'),
        ),
    ]
