# Generated by Django 4.1.5 on 2023-01-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0002_remove_snapshot_id_alter_snapshot_snapshot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='edge_table',
            field=models.ForeignKey(blank=True, help_text='All connections between nodes in the snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edges', to='toxit.node'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='node_table',
            field=models.ForeignKey(blank=True, help_text='All subreddit nodes related to the snapshot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='toxit.node'),
        ),
    ]
