# Generated by Django 4.1.5 on 2023-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0003_alter_snapshot_edge_table_alter_snapshot_node_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='snapshot_name',
            field=models.CharField(blank=True, help_text='optional way to name the snapshot', max_length=128, null=True),
        ),
    ]
