# Generated by Django 4.1.5 on 2023-01-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0004_snapshot_snapshot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='edge_table',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='node_table',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Snapshot',
        ),
    ]
