# Generated by Django 4.1.5 on 2023-01-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toxit', '0005_remove_snapshot_edge_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_name', models.CharField(max_length=24)),
                ('toxicity_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_mod_count', models.PositiveIntegerField(default=0, help_text='Arc weight representing the number of shared moderators between subreddits.')),
                ('shared_mod_sim', models.FloatField(default=0, help_text='Arc weight representing some magic stats number with a fancy name.')),
                ('end_node', models.ForeignKey(help_text='Destination of edge', on_delete=django.db.models.deletion.CASCADE, related_name='end', to='toxit.node')),
                ('start_node', models.ForeignKey(help_text='Origin of edge', on_delete=django.db.models.deletion.CASCADE, related_name='start', to='toxit.node')),
            ],
        ),
    ]
