# Generated by Django 4.1.5 on 2023-01-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0006_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('start_node', 'end_node')},
        ),
    ]
