# Generated by Django 4.1.5 on 2023-01-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0007_alter_edge_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ThingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shit', to='toxit.option')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuck', to='toxit.thing')),
            ],
            options={
                'unique_together': {('thing', 'option')},
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='options',
            field=models.ManyToManyField(through='toxit.ThingOption', to='toxit.option'),
        ),
    ]
