# Generated by Django 4.1.5 on 2023-01-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toxit', '0008_option_thing_thingoption_thing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='options',
        ),
        migrations.AlterUniqueTogether(
            name='thingoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thingoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='thingoption',
            name='thing',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
        migrations.DeleteModel(
            name='ThingOption',
        ),
    ]
